version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.1
jobs:
  build:
    working_directory: ~/ng-project
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - browser-tools/install-browser-tools:
        chrome-version: "116.0.5845.96" # TODO: remove -> https://github.com/CircleCI-Public/browser-tools-orb/issues/75
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - restore_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm install --save-dev firebase-tools
      - save_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      #- run:
      #    name: "Run test"
      #    command: npm run test
      - run:
          name: "Build application for production"
          command: npm run build
      - run:
          name: "Generate Service Account Authentication"
          command: 'echo "$GOOGLE_APPLICATION_CREDENTIALS_BASE_64" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS'
      - run:
          name: "Deploy app to Firebase Hosting"
          command: |
            echo $FIREBASE_TOKEN > credentials.json
            GOOGLE_APPLICATION_CREDENTIALS=credentials.json firebase deploy
      - run:
          name: "Remove credentials file"
          command: "rm $GOOGLE_APPLICATION_CREDENTIALS"